### ISSUE TITLE
Citation bar chart is not properly displayed when there are too many references

### ISSUE THREAD

**Issue by zhangfanmark** [SlicerDMRI/slicerdmri.github.io#7]
When there are too many citations in one year (e.g. 2017), each line in the bar becomes too thin to see. Need to update the bib-publication-list (perhaps they have updated for this ) to fix.

**Comment by ljod** [comment]
sounds like a good problem to have :)

**Comment by zhangfanmark** [comment]
Fixed by enlarging the height of graph.

**Comment by ljod** [comment]
Awesome we have increased citations!

**Comment by ljod** [comment]
Hi Fan please update the line on the page that says what are the keywords. Please add SlicerDMRI

**Comment by ljod** [comment]
Minor request: when I click on the bib link after each entry, I do not see the comments. Could you modify to display also the comment showing how/that they used the software? Thanks. This looks great!

**Comment by zhangfanmark** [comment]
Hi Lauren,

We have the comment, which is displayed as the first entry in the bibtex. Just for some of our papers, I did not put the comment.

**Comment by ljod** [comment]
Oh maybe I looked at the bottom of each entry not the top, since I did not see a comment. You mean the bibtex display when you click on each of the small bib links by each displayed citation under the bar graph?

**Comment by zhangfanmark** [comment]
Yes, it is. I put the comment at the end of each citation in the bib source file. But, when displaying by clicking the bib links, the comment show as the first one.
